### ISSUE TITLE
Regarding Predicting Accuracy [ y_test vs y_pred ]

### ISSUE THREAD

**Issue by asquares** [KristiyanVachev/Question-Generation#10]
On training:

y_test.value_counts() is:
False    828
True      40

i.e. 40 of 868 are marked 'True' in test set.

y_pred_series.value_count() is:
True     657
False    211

that shows 657 values have been marked True which reflects a lot of True values, which actually reflects a lot of false positive values (619) i.e. 657 =  38 (Actual Tru, i.e TP ) + 619 (Predicted True but actually are False i.e FPs) 

In fact the confusion_matrix(y_test, y_pred) shows the same:
array([[209, **619**],
       [  2,  **38**]])

It's quite clear that the correct answers predicted is very high i.e. 38/40. 

In light of above results:
a. I am unable to understand you following conclusion as the overall accuracy considering True Negatives(209) is not good. 

"Seems like I'm super biased for towards correct answers." But as I found during the Data exploration, there are a lot more answer-worthy words that are just not labeled since, I guess the Mechanical Turks had the job to label just 5. So, who knows, maybe I did some black magic and managed to extract all the answer worthy words!

b. Secondly, can you elaborate what was your aim in regards to predicting 'isAnswer'? Is it related to finding only relevant answers as that of the original dataset i.e. (40)? Or you intended to extract new words which could serve as answers for more questions and if that's correct, which part of confusion matrix results you consider to be potential relevant answers beyond what is provided in data set?

**Comment by KristiyanVachev** [comment]
Regarding a. 
The original dataset is not created for the purpose of labeling all words which are suitable to be an answer to a question. In fact only about 5 phrases are market as such out of the entire paragraph, where it is clear that basically 3-4 words per sentence could be used as such answer candidates. The confusion matrix is just a standard metric, which in this case is not very relevant since we do not have an actual dataset that is showing us all of the isAnswer phrases. 

Regarding b.
The purpose of predicting isAnswer is to decide which words could be used to build a question around them (in this case only a cloze style question, tough this is an approach also used with transformers). Since most of the words are marked as True, a better  way to extract only a few answer candidates is to use the probability that the Naive Bayes algorithm is giving us, and with it get only the top answers candidates that are used to build the questions from.
