### ISSUE TITLE
ValueError: operands could not be broadcast together with shapes (230, 121) (83, )

### ISSUE THREAD

**Issue by parthpanchal3399** [KristiyanVachev/Question-Generation#11]
So first of all I cloned your repo to try out the code. The Demo.ipynb worked fine as expected (without any change in input text). However after giving my own text as input, I am getting error in the naive bias file of sklearn.
The error: 

![image](https://user-images.githubusercontent.com/51913848/108314156-6f119100-71df-11eb-8a92-76215b9c13dd.png)

I tried a lot to debug the issue, however since I am new to ML and Data science in general, I was not able to get the issue fixed. Also the error is in the sklearn's files, so not sure what's causing the issue. I even tried downgrading my python and all the modules so as to match yours and rebuilt the model, but still it gave the same error message in Predict.ipynb. I saw a lot of people were facing the same issue in the 'issue' section of your repo

It would be greatly helpful if you could point me in the right direction so that I can resolve this issue.

**Comment by KristiyanVachev** [comment]
I have fixed the issue in the latest commit.  Please verify that it is working on your site as well :) 

The problem arises from the different amount of features that the new text has and what the Naive Bayes predictor has been trained on. This is caused by the one-hot encoded features of the POS and DEP tags. 

Basically, if your text has 4 kinds of POS tags (NOUN, PROPN, ADJ, ADP) it creates 4 features (is_NOUN, is_PROPN is_ADJ, is_ADP), but if the predictor is trained on only 3 of them, then it cannot do the matrix calculations properly. In your case one has 121 features and the other has 83.

**Comment by parthpanchal3399** [comment]
Thanks for looking into this.
I'll check and verify if its working on my side as well and let you know.
