### ISSUE TITLE
What if the answers were sentences instead of one word?

### ISSUE THREAD

**Issue by revantt** [KristiyanVachev/Question-Generation#3]
And the incorrect answers would also be sentences... What can I do for that?

**Comment by KristiyanVachev** [comment]
Single words are easier, because you are going trough every word once and you assign the features for that word (e.g. part of speech, starts with capital letter...)
If you were working with n-grams (pair of words) you would have to go trough the text multiple times - one iteration for 1, 2, 3, 4... word counts. Also the features get mixed (e.g. first word is a noun, the second is a verb)

That being said, nothing is stopping you from working with n-grams. It's just going to be more difficult to assign correct and meaningful features.
