### ISSUE TITLE
Database

### ISSUE THREAD

**Issue by asmusale** [KristiyanVachev/Question-Generation#7]
Hello sir, can you add database file or sql file which help to store created mcq in database

**Comment by mohabedalgani** [comment]
Hi..
the file of the following is missing
data/embeddings/**word2vec-glove.6B.300d.txt**

Kindly upload it to have a chance testing the library

**Comment by KristiyanVachev** [comment]
Hello, storing the files in a database is not a goal I have with this simple demo.

And @mohabedalgani , [here ](https://github.com/KristiyanVachev/Question-Generation/tree/master/data)are instructions on downloading the files, since I do not have the right to upload them (and they are also too large).
