### ISSUE TITLE
ValueError: operands could not be broadcast together with shapes (2448,122) (121,)

### ISSUE THREAD

**Issue by mady143** [KristiyanVachev/Question-Generation#8]
Hi,
I clone your project and made some changes like reading form pdf and as well txt file dynamically rote an API but hen i was trying to read the pdf file and process the file getting an error like **ValueError: operands could not be broadcast together with shapes (2448,122) (121,)**
and i have seen this same issue in resolved issue section i tried of that requirements provided their i had run the same requirements but i was unable to resolve that issue..

Thanks and Regards,
Manikantha Sekhar...

**Comment by jersey15** [comment]
Hi @mady143,

I had the same problem and invested some time to figure it out. So, I figured out that if in your input text is the word "like" the function OneHotEncoding inserts a column that is not removed before inserting it into the pre-trained model. 

How to fix it?
I just replaced the word "like" and run the code again and it worked! 
Hopefully, it worked for you too!

**Comment by inversepolymath** [comment]
I had a similar problem with the word 'despite'

**Comment by sumukhbhat2701** [comment]
Hey guys, was someone able to fix the issue? It would of great help to me!

**Comment by parthpanchal3399** [comment]
Hello,
I faced the same issue, however I found out that if you use the same .pkl that KristiyanVachev provided in /data/pickles/ we just get a warning **UserWarning: Trying to unpickle estimator GaussianNB from version 0.20.3 when using version 0.24.1. This might lead to breaking code or invalid results. Use at your own risk.
  warnings.warn**

Now I assume this is because the model was trained using sklearn 0.20.3 and my system has the latest sklearn.
So I tried re-training the model but then I get this error  **ValueError: operands could not be broadcast together with shapes**

So one fix could be install older sklearn and then run the demo.ipynb

I hope my answer makes sense

**Comment by parthpanchal3399** [comment]
Facing same issue! Can you help @KristiyanVachev 
I am able to run the demo.ipynb as it is, however if I change the sample text, it gives this error:
\appdata\local\programs\python\python38\lib\site-packages\sklearn\naive_bayes.py in _joint_log_likelihood(self, X)
    451             jointi = np.log(self.class_prior_[i])
    452             n_ij = - 0.5 * np.sum(np.log(2. * np.pi * self.sigma_[i, :]))
--> 453             n_ij -= 0.5 * np.sum(((X - self.theta_[i, :]) ** 2) /
    454                                  (self.sigma_[i, :]), 1)
    455             joint_log_likelihood.append(jointi + n_ij)

ValueError: operands could not be broadcast together with shapes (230,122) (121,)

**Comment by parthpanchal3399** [comment]
As per jersey15 and inversepolymath's answer, I can say that if the input text doesn't have  "Like" and "despite" (maybe some more words could be the reason too), AND if you are using the pickle from the repo (ie not re-training the model), it works flawlessly.
Not sure why so

**Comment by KristiyanVachev** [comment]
I have fixed the issue in the latest commit. 

The problem arises from the different amount of features that the new text has and what the Naive Bayes predictor has been trained on. This is caused by the one-hot encoded features of the POS and DEP tags.

Basically, if your text has 4 kinds of POS tags (NOUN, PROPN, ADJ, ADP) it creates 4 features (is_NOUN, is_PROPN is_ADJ, is_ADP), but if the predictor is trained on only 3 of them, then it cannot do the matrix calculations properly. In your case one has 121 features and the other has 83.

Removing words like "like" and "despite" may coincidentally fix the problem, but it is not a general solution. What I did was saving the names of the features along with the predictor. Then when you extract the features for your desired text they are matched exactly to the ones saved from the predictor and any features that were not present are removed.
